//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyUbigeo
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UbigeoDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Mant")]
    public partial class UbigeoDC : object
    {
        
        private string DepartamentoField;
        
        private string DistritoField;
        
        private string IdDepaField;
        
        private string IdDistField;
        
        private string IdProvField;
        
        private string ProvinciaField;
        
        private string cod_ubigeoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento
        {
            get
            {
                return this.DepartamentoField;
            }
            set
            {
                this.DepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito
        {
            get
            {
                return this.DistritoField;
            }
            set
            {
                this.DistritoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdDepa
        {
            get
            {
                return this.IdDepaField;
            }
            set
            {
                this.IdDepaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdDist
        {
            get
            {
                return this.IdDistField;
            }
            set
            {
                this.IdDistField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdProv
        {
            get
            {
                return this.IdProvField;
            }
            set
            {
                this.IdProvField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia
        {
            get
            {
                return this.ProvinciaField;
            }
            set
            {
                this.ProvinciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_ubigeo
        {
            get
            {
                return this.cod_ubigeoField;
            }
            set
            {
                this.cod_ubigeoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyUbigeo.IServicioUbigeo")]
    public interface IServicioUbigeo
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/ListarUbigeo_Departamento", ReplyAction="http://tempuri.org/IServicioUbigeo/ListarUbigeo_DepartamentoResponse")]
        System.Collections.Generic.List<ProxyUbigeo.UbigeoDC> ListarUbigeo_Departamento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/ListarUbigeo_Departamento", ReplyAction="http://tempuri.org/IServicioUbigeo/ListarUbigeo_DepartamentoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyUbigeo.UbigeoDC>> ListarUbigeo_DepartamentoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/ListarUbigeo_ProvinciasDepartamento", ReplyAction="http://tempuri.org/IServicioUbigeo/ListarUbigeo_ProvinciasDepartamentoResponse")]
        System.Collections.Generic.List<ProxyUbigeo.UbigeoDC> ListarUbigeo_ProvinciasDepartamento(string strIdDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/ListarUbigeo_ProvinciasDepartamento", ReplyAction="http://tempuri.org/IServicioUbigeo/ListarUbigeo_ProvinciasDepartamentoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyUbigeo.UbigeoDC>> ListarUbigeo_ProvinciasDepartamentoAsync(string strIdDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/ListarUbigeo_DistritoProvinciaDepartamento", ReplyAction="http://tempuri.org/IServicioUbigeo/ListarUbigeo_DistritoProvinciaDepartamentoResp" +
            "onse")]
        System.Collections.Generic.List<ProxyUbigeo.UbigeoDC> ListarUbigeo_DistritoProvinciaDepartamento(string strIdDepartamento, string strIdProvincia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/ListarUbigeo_DistritoProvinciaDepartamento", ReplyAction="http://tempuri.org/IServicioUbigeo/ListarUbigeo_DistritoProvinciaDepartamentoResp" +
            "onse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyUbigeo.UbigeoDC>> ListarUbigeo_DistritoProvinciaDepartamentoAsync(string strIdDepartamento, string strIdProvincia);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServicioUbigeoChannel : ProxyUbigeo.IServicioUbigeo, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServicioUbigeoClient : System.ServiceModel.ClientBase<ProxyUbigeo.IServicioUbigeo>, ProxyUbigeo.IServicioUbigeo
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioUbigeoClient() : 
                base(ServicioUbigeoClient.GetDefaultBinding(), ServicioUbigeoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioUbigeo.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioUbigeoClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioUbigeoClient.GetBindingForEndpoint(endpointConfiguration), ServicioUbigeoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioUbigeoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioUbigeoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioUbigeoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioUbigeoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioUbigeoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ProxyUbigeo.UbigeoDC> ListarUbigeo_Departamento()
        {
            return base.Channel.ListarUbigeo_Departamento();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyUbigeo.UbigeoDC>> ListarUbigeo_DepartamentoAsync()
        {
            return base.Channel.ListarUbigeo_DepartamentoAsync();
        }
        
        public System.Collections.Generic.List<ProxyUbigeo.UbigeoDC> ListarUbigeo_ProvinciasDepartamento(string strIdDepartamento)
        {
            return base.Channel.ListarUbigeo_ProvinciasDepartamento(strIdDepartamento);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyUbigeo.UbigeoDC>> ListarUbigeo_ProvinciasDepartamentoAsync(string strIdDepartamento)
        {
            return base.Channel.ListarUbigeo_ProvinciasDepartamentoAsync(strIdDepartamento);
        }
        
        public System.Collections.Generic.List<ProxyUbigeo.UbigeoDC> ListarUbigeo_DistritoProvinciaDepartamento(string strIdDepartamento, string strIdProvincia)
        {
            return base.Channel.ListarUbigeo_DistritoProvinciaDepartamento(strIdDepartamento, strIdProvincia);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyUbigeo.UbigeoDC>> ListarUbigeo_DistritoProvinciaDepartamentoAsync(string strIdDepartamento, string strIdProvincia)
        {
            return base.Channel.ListarUbigeo_DistritoProvinciaDepartamentoAsync(strIdDepartamento, strIdProvincia);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioUbigeo))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioUbigeo))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_Mant/ServicioUbigeo/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioUbigeoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioUbigeo);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioUbigeoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioUbigeo);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioUbigeo,
        }
    }
}
