//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyMant
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MantDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Mant")]
    public partial class MantDC : object
    {
        
        private string Ape_cliField;
        
        private string Dni_CliField;
        
        private float Est_facField;
        
        private string EstadoFacturaField;
        
        private System.DateTime Fec_canField;
        
        private string Nom_cliField;
        
        private string Num_FacturaField;
        
        private string Raz_soc_cliField;
        
        private string Ruc_CliField;
        
        private System.DateTime fec_facField;
        
        private string idMantenimientoField;
        
        private string idVehiculoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_cli
        {
            get
            {
                return this.Ape_cliField;
            }
            set
            {
                this.Ape_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni_Cli
        {
            get
            {
                return this.Dni_CliField;
            }
            set
            {
                this.Dni_CliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Est_fac
        {
            get
            {
                return this.Est_facField;
            }
            set
            {
                this.Est_facField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoFactura
        {
            get
            {
                return this.EstadoFacturaField;
            }
            set
            {
                this.EstadoFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_can
        {
            get
            {
                return this.Fec_canField;
            }
            set
            {
                this.Fec_canField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_cli
        {
            get
            {
                return this.Nom_cliField;
            }
            set
            {
                this.Nom_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Num_Factura
        {
            get
            {
                return this.Num_FacturaField;
            }
            set
            {
                this.Num_FacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Raz_soc_cli
        {
            get
            {
                return this.Raz_soc_cliField;
            }
            set
            {
                this.Raz_soc_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruc_Cli
        {
            get
            {
                return this.Ruc_CliField;
            }
            set
            {
                this.Ruc_CliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fec_fac
        {
            get
            {
                return this.fec_facField;
            }
            set
            {
                this.fec_facField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idMantenimiento
        {
            get
            {
                return this.idMantenimientoField;
            }
            set
            {
                this.idMantenimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idVehiculo
        {
            get
            {
                return this.idVehiculoField;
            }
            set
            {
                this.idVehiculoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MantYearDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Mant")]
    public partial class MantYearDC : object
    {
        
        private float Costo_ManField;
        
        private string EstadoField;
        
        private short Estado_ManField;
        
        private System.DateTime FechaField;
        
        private string MantenimientoField;
        
        private string NombreCompletoField;
        
        private string Nombre_ManField;
        
        private string idMecanicoField;
        
        private string idVehiculoField;
        
        private short tipo_mantenimientoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Costo_Man
        {
            get
            {
                return this.Costo_ManField;
            }
            set
            {
                this.Costo_ManField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Estado_Man
        {
            get
            {
                return this.Estado_ManField;
            }
            set
            {
                this.Estado_ManField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mantenimiento
        {
            get
            {
                return this.MantenimientoField;
            }
            set
            {
                this.MantenimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCompleto
        {
            get
            {
                return this.NombreCompletoField;
            }
            set
            {
                this.NombreCompletoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_Man
        {
            get
            {
                return this.Nombre_ManField;
            }
            set
            {
                this.Nombre_ManField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idMecanico
        {
            get
            {
                return this.idMecanicoField;
            }
            set
            {
                this.idMecanicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idVehiculo
        {
            get
            {
                return this.idVehiculoField;
            }
            set
            {
                this.idVehiculoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short tipo_mantenimiento
        {
            get
            {
                return this.tipo_mantenimientoField;
            }
            set
            {
                this.tipo_mantenimientoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyMant.IMantenimiento")]
    public interface IMantenimiento
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimiento/ListarMantenimientoFechas", ReplyAction="http://tempuri.org/IMantenimiento/ListarMantenimientoFechasResponse")]
        System.Collections.Generic.List<ProxyMant.MantDC> ListarMantenimientoFechas(System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimiento/ListarMantenimientoFechas", ReplyAction="http://tempuri.org/IMantenimiento/ListarMantenimientoFechasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyMant.MantDC>> ListarMantenimientoFechasAsync(System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimiento/ListarMantenimientoYear", ReplyAction="http://tempuri.org/IMantenimiento/ListarMantenimientoYearResponse")]
        System.Collections.Generic.List<ProxyMant.MantYearDC> ListarMantenimientoYear(short Year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimiento/ListarMantenimientoYear", ReplyAction="http://tempuri.org/IMantenimiento/ListarMantenimientoYearResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyMant.MantYearDC>> ListarMantenimientoYearAsync(short Year);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IMantenimientoChannel : ProxyMant.IMantenimiento, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class MantenimientoClient : System.ServiceModel.ClientBase<ProxyMant.IMantenimiento>, ProxyMant.IMantenimiento
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MantenimientoClient() : 
                base(MantenimientoClient.GetDefaultBinding(), MantenimientoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMantenimiento.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MantenimientoClient(EndpointConfiguration endpointConfiguration) : 
                base(MantenimientoClient.GetBindingForEndpoint(endpointConfiguration), MantenimientoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MantenimientoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MantenimientoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MantenimientoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MantenimientoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MantenimientoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ProxyMant.MantDC> ListarMantenimientoFechas(System.DateTime fecini, System.DateTime fecfin)
        {
            return base.Channel.ListarMantenimientoFechas(fecini, fecfin);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyMant.MantDC>> ListarMantenimientoFechasAsync(System.DateTime fecini, System.DateTime fecfin)
        {
            return base.Channel.ListarMantenimientoFechasAsync(fecini, fecfin);
        }
        
        public System.Collections.Generic.List<ProxyMant.MantYearDC> ListarMantenimientoYear(short Year)
        {
            return base.Channel.ListarMantenimientoYear(Year);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyMant.MantYearDC>> ListarMantenimientoYearAsync(short Year)
        {
            return base.Channel.ListarMantenimientoYearAsync(Year);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMantenimiento))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMantenimiento))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_Mant/Mantenimiento/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MantenimientoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMantenimiento);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MantenimientoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMantenimiento);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMantenimiento,
        }
    }
}
