//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenimiento_WCF_MVC.ProxyMantenimientos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MantDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Mant")]
    [System.SerializableAttribute()]
    public partial class MantDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ape_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dni_CliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float Est_facField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_canField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Num_FacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Raz_soc_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ruc_CliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fec_facField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idMantenimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idVehiculoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_cli {
            get {
                return this.Ape_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Ape_cliField, value) != true)) {
                    this.Ape_cliField = value;
                    this.RaisePropertyChanged("Ape_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni_Cli {
            get {
                return this.Dni_CliField;
            }
            set {
                if ((object.ReferenceEquals(this.Dni_CliField, value) != true)) {
                    this.Dni_CliField = value;
                    this.RaisePropertyChanged("Dni_Cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Est_fac {
            get {
                return this.Est_facField;
            }
            set {
                if ((this.Est_facField.Equals(value) != true)) {
                    this.Est_facField = value;
                    this.RaisePropertyChanged("Est_fac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoFactura {
            get {
                return this.EstadoFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoFacturaField, value) != true)) {
                    this.EstadoFacturaField = value;
                    this.RaisePropertyChanged("EstadoFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_can {
            get {
                return this.Fec_canField;
            }
            set {
                if ((this.Fec_canField.Equals(value) != true)) {
                    this.Fec_canField = value;
                    this.RaisePropertyChanged("Fec_can");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_cli {
            get {
                return this.Nom_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_cliField, value) != true)) {
                    this.Nom_cliField = value;
                    this.RaisePropertyChanged("Nom_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Num_Factura {
            get {
                return this.Num_FacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.Num_FacturaField, value) != true)) {
                    this.Num_FacturaField = value;
                    this.RaisePropertyChanged("Num_Factura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Raz_soc_cli {
            get {
                return this.Raz_soc_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Raz_soc_cliField, value) != true)) {
                    this.Raz_soc_cliField = value;
                    this.RaisePropertyChanged("Raz_soc_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruc_Cli {
            get {
                return this.Ruc_CliField;
            }
            set {
                if ((object.ReferenceEquals(this.Ruc_CliField, value) != true)) {
                    this.Ruc_CliField = value;
                    this.RaisePropertyChanged("Ruc_Cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fec_fac {
            get {
                return this.fec_facField;
            }
            set {
                if ((this.fec_facField.Equals(value) != true)) {
                    this.fec_facField = value;
                    this.RaisePropertyChanged("fec_fac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idMantenimiento {
            get {
                return this.idMantenimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.idMantenimientoField, value) != true)) {
                    this.idMantenimientoField = value;
                    this.RaisePropertyChanged("idMantenimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idVehiculo {
            get {
                return this.idVehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.idVehiculoField, value) != true)) {
                    this.idVehiculoField = value;
                    this.RaisePropertyChanged("idVehiculo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyMantenimientos.IMantenimiento")]
    public interface IMantenimiento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimiento/ListarMantenimientoFechas", ReplyAction="http://tempuri.org/IMantenimiento/ListarMantenimientoFechasResponse")]
        Mantenimiento_WCF_MVC.ProxyMantenimientos.MantDC[] ListarMantenimientoFechas(System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimiento/ListarMantenimientoFechas", ReplyAction="http://tempuri.org/IMantenimiento/ListarMantenimientoFechasResponse")]
        System.Threading.Tasks.Task<Mantenimiento_WCF_MVC.ProxyMantenimientos.MantDC[]> ListarMantenimientoFechasAsync(System.DateTime fecini, System.DateTime fecfin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMantenimientoChannel : Mantenimiento_WCF_MVC.ProxyMantenimientos.IMantenimiento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MantenimientoClient : System.ServiceModel.ClientBase<Mantenimiento_WCF_MVC.ProxyMantenimientos.IMantenimiento>, Mantenimiento_WCF_MVC.ProxyMantenimientos.IMantenimiento {
        
        public MantenimientoClient() {
        }
        
        public MantenimientoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MantenimientoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MantenimientoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MantenimientoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Mantenimiento_WCF_MVC.ProxyMantenimientos.MantDC[] ListarMantenimientoFechas(System.DateTime fecini, System.DateTime fecfin) {
            return base.Channel.ListarMantenimientoFechas(fecini, fecfin);
        }
        
        public System.Threading.Tasks.Task<Mantenimiento_WCF_MVC.ProxyMantenimientos.MantDC[]> ListarMantenimientoFechasAsync(System.DateTime fecini, System.DateTime fecfin) {
            return base.Channel.ListarMantenimientoFechasAsync(fecini, fecfin);
        }
    }
}
