//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Mant
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MANTENIMIENTO : DbContext
    {
        public MANTENIMIENTO()
            : base("name=MANTENIMIENTO")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_Act_Man> Tb_Act_Man { get; set; }
        public virtual DbSet<Tb_Cliente> Tb_Cliente { get; set; }
        public virtual DbSet<Tb_DetalleFactura> Tb_DetalleFactura { get; set; }
        public virtual DbSet<Tb_Factura> Tb_Factura { get; set; }
        public virtual DbSet<Tb_Mant_Detalle> Tb_Mant_Detalle { get; set; }
        public virtual DbSet<Tb_Mantenimiento> Tb_Mantenimiento { get; set; }
        public virtual DbSet<Tb_Marca> Tb_Marca { get; set; }
        public virtual DbSet<Tb_Mecanico> Tb_Mecanico { get; set; }
        public virtual DbSet<Tb_Repuesto> Tb_Repuesto { get; set; }
        public virtual DbSet<Tb_Sist_Veh> Tb_Sist_Veh { get; set; }
        public virtual DbSet<Tb_Sub_Sist_Veh> Tb_Sub_Sist_Veh { get; set; }
        public virtual DbSet<Tb_Ubigeo> Tb_Ubigeo { get; set; }
        public virtual DbSet<Tb_Usuario> Tb_Usuario { get; set; }
        public virtual DbSet<Tb_Vehiculo> Tb_Vehiculo { get; set; }
        public virtual DbSet<Tb_Cliente_Aud> Tb_Cliente_Aud { get; set; }
        public virtual DbSet<Tb_Mecanico_Aud> Tb_Mecanico_Aud { get; set; }
        public virtual DbSet<Tb_Repuesto_Aud> Tb_Repuesto_Aud { get; set; }
        public virtual DbSet<Tb_Vehiculo_Aud> Tb_Vehiculo_Aud { get; set; }
    
        public virtual ObjectResult<usp_ClientesFechas_Result> usp_ClientesFechas(string idCliente, Nullable<System.DateTime> vFec_Inicio, Nullable<System.DateTime> vFec_Fin)
        {
            var idClienteParameter = idCliente != null ?
                new ObjectParameter("idCliente", idCliente) :
                new ObjectParameter("idCliente", typeof(string));
    
            var vFec_InicioParameter = vFec_Inicio.HasValue ?
                new ObjectParameter("vFec_Inicio", vFec_Inicio) :
                new ObjectParameter("vFec_Inicio", typeof(System.DateTime));
    
            var vFec_FinParameter = vFec_Fin.HasValue ?
                new ObjectParameter("vFec_Fin", vFec_Fin) :
                new ObjectParameter("vFec_Fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ClientesFechas_Result>("usp_ClientesFechas", idClienteParameter, vFec_InicioParameter, vFec_FinParameter);
        }
    
        public virtual ObjectResult<usp_MantFechas_Result> usp_MantFechas(Nullable<System.DateTime> vFec_Inicio, Nullable<System.DateTime> vFec_Fin)
        {
            var vFec_InicioParameter = vFec_Inicio.HasValue ?
                new ObjectParameter("vFec_Inicio", vFec_Inicio) :
                new ObjectParameter("vFec_Inicio", typeof(System.DateTime));
    
            var vFec_FinParameter = vFec_Fin.HasValue ?
                new ObjectParameter("vFec_Fin", vFec_Fin) :
                new ObjectParameter("vFec_Fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_MantFechas_Result>("usp_MantFechas", vFec_InicioParameter, vFec_FinParameter);
        }
    
        public virtual ObjectResult<usp_MecanicoFechas_Result> usp_MecanicoFechas(string idMecanico, Nullable<System.DateTime> vFec_Inicio, Nullable<System.DateTime> vFec_Fin)
        {
            var idMecanicoParameter = idMecanico != null ?
                new ObjectParameter("idMecanico", idMecanico) :
                new ObjectParameter("idMecanico", typeof(string));
    
            var vFec_InicioParameter = vFec_Inicio.HasValue ?
                new ObjectParameter("vFec_Inicio", vFec_Inicio) :
                new ObjectParameter("vFec_Inicio", typeof(System.DateTime));
    
            var vFec_FinParameter = vFec_Fin.HasValue ?
                new ObjectParameter("vFec_Fin", vFec_Fin) :
                new ObjectParameter("vFec_Fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_MecanicoFechas_Result>("usp_MecanicoFechas", idMecanicoParameter, vFec_InicioParameter, vFec_FinParameter);
        }
    
        public virtual ObjectResult<usp_RankingClieMantAños_Result> usp_RankingClieMantAños(Nullable<int> año)
        {
            var añoParameter = año.HasValue ?
                new ObjectParameter("año", año) :
                new ObjectParameter("año", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RankingClieMantAños_Result>("usp_RankingClieMantAños", añoParameter);
        }
    
        public virtual ObjectResult<usp_RankingMantMecAños_Result> usp_RankingMantMecAños(Nullable<int> año)
        {
            var añoParameter = año.HasValue ?
                new ObjectParameter("año", año) :
                new ObjectParameter("año", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RankingMantMecAños_Result>("usp_RankingMantMecAños", añoParameter);
        }
    
        public virtual ObjectResult<usp_RankingVehiculosMantAños_Result> usp_RankingVehiculosMantAños(Nullable<int> año)
        {
            var añoParameter = año.HasValue ?
                new ObjectParameter("año", año) :
                new ObjectParameter("año", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RankingVehiculosMantAños_Result>("usp_RankingVehiculosMantAños", añoParameter);
        }
    
        public virtual ObjectResult<usp_VehiculoFechas_Result> usp_VehiculoFechas(string idVehiculo, Nullable<System.DateTime> vFec_Inicio, Nullable<System.DateTime> vFec_Fin)
        {
            var idVehiculoParameter = idVehiculo != null ?
                new ObjectParameter("idVehiculo", idVehiculo) :
                new ObjectParameter("idVehiculo", typeof(string));
    
            var vFec_InicioParameter = vFec_Inicio.HasValue ?
                new ObjectParameter("vFec_Inicio", vFec_Inicio) :
                new ObjectParameter("vFec_Inicio", typeof(System.DateTime));
    
            var vFec_FinParameter = vFec_Fin.HasValue ?
                new ObjectParameter("vFec_Fin", vFec_Fin) :
                new ObjectParameter("vFec_Fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_VehiculoFechas_Result>("usp_VehiculoFechas", idVehiculoParameter, vFec_InicioParameter, vFec_FinParameter);
        }
    
        public virtual int usp_ActualizarCliente(string vcod, string vcod_Ubigeo, string vnom, string vape, string vdir, string vruc_cli, string vtel, Nullable<System.DateTime> vfec_nac_cli, string vcorreo, string vsex, string vdni, string vUsu_Ult_Mod, Nullable<int> vEst_cli, Nullable<int> vTip)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            var vcod_UbigeoParameter = vcod_Ubigeo != null ?
                new ObjectParameter("vcod_Ubigeo", vcod_Ubigeo) :
                new ObjectParameter("vcod_Ubigeo", typeof(string));
    
            var vnomParameter = vnom != null ?
                new ObjectParameter("vnom", vnom) :
                new ObjectParameter("vnom", typeof(string));
    
            var vapeParameter = vape != null ?
                new ObjectParameter("vape", vape) :
                new ObjectParameter("vape", typeof(string));
    
            var vdirParameter = vdir != null ?
                new ObjectParameter("vdir", vdir) :
                new ObjectParameter("vdir", typeof(string));
    
            var vruc_cliParameter = vruc_cli != null ?
                new ObjectParameter("vruc_cli", vruc_cli) :
                new ObjectParameter("vruc_cli", typeof(string));
    
            var vtelParameter = vtel != null ?
                new ObjectParameter("vtel", vtel) :
                new ObjectParameter("vtel", typeof(string));
    
            var vfec_nac_cliParameter = vfec_nac_cli.HasValue ?
                new ObjectParameter("vfec_nac_cli", vfec_nac_cli) :
                new ObjectParameter("vfec_nac_cli", typeof(System.DateTime));
    
            var vcorreoParameter = vcorreo != null ?
                new ObjectParameter("vcorreo", vcorreo) :
                new ObjectParameter("vcorreo", typeof(string));
    
            var vsexParameter = vsex != null ?
                new ObjectParameter("vsex", vsex) :
                new ObjectParameter("vsex", typeof(string));
    
            var vdniParameter = vdni != null ?
                new ObjectParameter("vdni", vdni) :
                new ObjectParameter("vdni", typeof(string));
    
            var vUsu_Ult_ModParameter = vUsu_Ult_Mod != null ?
                new ObjectParameter("vUsu_Ult_Mod", vUsu_Ult_Mod) :
                new ObjectParameter("vUsu_Ult_Mod", typeof(string));
    
            var vEst_cliParameter = vEst_cli.HasValue ?
                new ObjectParameter("vEst_cli", vEst_cli) :
                new ObjectParameter("vEst_cli", typeof(int));
    
            var vTipParameter = vTip.HasValue ?
                new ObjectParameter("vTip", vTip) :
                new ObjectParameter("vTip", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarCliente", vcodParameter, vcod_UbigeoParameter, vnomParameter, vapeParameter, vdirParameter, vruc_cliParameter, vtelParameter, vfec_nac_cliParameter, vcorreoParameter, vsexParameter, vdniParameter, vUsu_Ult_ModParameter, vEst_cliParameter, vTipParameter);
        }
    
        public virtual int usp_EliminarCliente(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarCliente", vcodParameter);
        }
    
        public virtual int usp_InsertarCliente(string vcod_Ubigeo, string vnom, string vape, string vdir, string vruc_cli, string vtel, Nullable<System.DateTime> vfec_nac_cli, string vcorreo, string vsex, string vdni, string vUsu_Registro, Nullable<int> vEst_cli, Nullable<int> vTip)
        {
            var vcod_UbigeoParameter = vcod_Ubigeo != null ?
                new ObjectParameter("vcod_Ubigeo", vcod_Ubigeo) :
                new ObjectParameter("vcod_Ubigeo", typeof(string));
    
            var vnomParameter = vnom != null ?
                new ObjectParameter("vnom", vnom) :
                new ObjectParameter("vnom", typeof(string));
    
            var vapeParameter = vape != null ?
                new ObjectParameter("vape", vape) :
                new ObjectParameter("vape", typeof(string));
    
            var vdirParameter = vdir != null ?
                new ObjectParameter("vdir", vdir) :
                new ObjectParameter("vdir", typeof(string));
    
            var vruc_cliParameter = vruc_cli != null ?
                new ObjectParameter("vruc_cli", vruc_cli) :
                new ObjectParameter("vruc_cli", typeof(string));
    
            var vtelParameter = vtel != null ?
                new ObjectParameter("vtel", vtel) :
                new ObjectParameter("vtel", typeof(string));
    
            var vfec_nac_cliParameter = vfec_nac_cli.HasValue ?
                new ObjectParameter("vfec_nac_cli", vfec_nac_cli) :
                new ObjectParameter("vfec_nac_cli", typeof(System.DateTime));
    
            var vcorreoParameter = vcorreo != null ?
                new ObjectParameter("vcorreo", vcorreo) :
                new ObjectParameter("vcorreo", typeof(string));
    
            var vsexParameter = vsex != null ?
                new ObjectParameter("vsex", vsex) :
                new ObjectParameter("vsex", typeof(string));
    
            var vdniParameter = vdni != null ?
                new ObjectParameter("vdni", vdni) :
                new ObjectParameter("vdni", typeof(string));
    
            var vUsu_RegistroParameter = vUsu_Registro != null ?
                new ObjectParameter("vUsu_Registro", vUsu_Registro) :
                new ObjectParameter("vUsu_Registro", typeof(string));
    
            var vEst_cliParameter = vEst_cli.HasValue ?
                new ObjectParameter("vEst_cli", vEst_cli) :
                new ObjectParameter("vEst_cli", typeof(int));
    
            var vTipParameter = vTip.HasValue ?
                new ObjectParameter("vTip", vTip) :
                new ObjectParameter("vTip", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarCliente", vcod_UbigeoParameter, vnomParameter, vapeParameter, vdirParameter, vruc_cliParameter, vtelParameter, vfec_nac_cliParameter, vcorreoParameter, vsexParameter, vdniParameter, vUsu_RegistroParameter, vEst_cliParameter, vTipParameter);
        }
    
        public virtual ObjectResult<usp_ListarClienteGrilla_Result> usp_ListarClienteGrilla()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarClienteGrilla_Result>("usp_ListarClienteGrilla");
        }
    
        public virtual int usp_ActualizarMecanico(string idmec, string cod_ubigeo, string nom_mec, string ape_mec, string doc_iden, string dir_mecanico, Nullable<System.DateTime> fech_ingreso, string tel_mec, Nullable<System.DateTime> fec_nac, string sexo, string espe_mec, string centro_estudio, string correo_mec, string usu_ult_mod, Nullable<int> est_mec)
        {
            var idmecParameter = idmec != null ?
                new ObjectParameter("idmec", idmec) :
                new ObjectParameter("idmec", typeof(string));
    
            var cod_ubigeoParameter = cod_ubigeo != null ?
                new ObjectParameter("cod_ubigeo", cod_ubigeo) :
                new ObjectParameter("cod_ubigeo", typeof(string));
    
            var nom_mecParameter = nom_mec != null ?
                new ObjectParameter("nom_mec", nom_mec) :
                new ObjectParameter("nom_mec", typeof(string));
    
            var ape_mecParameter = ape_mec != null ?
                new ObjectParameter("ape_mec", ape_mec) :
                new ObjectParameter("ape_mec", typeof(string));
    
            var doc_idenParameter = doc_iden != null ?
                new ObjectParameter("doc_iden", doc_iden) :
                new ObjectParameter("doc_iden", typeof(string));
    
            var dir_mecanicoParameter = dir_mecanico != null ?
                new ObjectParameter("dir_mecanico", dir_mecanico) :
                new ObjectParameter("dir_mecanico", typeof(string));
    
            var fech_ingresoParameter = fech_ingreso.HasValue ?
                new ObjectParameter("fech_ingreso", fech_ingreso) :
                new ObjectParameter("fech_ingreso", typeof(System.DateTime));
    
            var tel_mecParameter = tel_mec != null ?
                new ObjectParameter("tel_mec", tel_mec) :
                new ObjectParameter("tel_mec", typeof(string));
    
            var fec_nacParameter = fec_nac.HasValue ?
                new ObjectParameter("fec_nac", fec_nac) :
                new ObjectParameter("fec_nac", typeof(System.DateTime));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("sexo", sexo) :
                new ObjectParameter("sexo", typeof(string));
    
            var espe_mecParameter = espe_mec != null ?
                new ObjectParameter("espe_mec", espe_mec) :
                new ObjectParameter("espe_mec", typeof(string));
    
            var centro_estudioParameter = centro_estudio != null ?
                new ObjectParameter("centro_estudio", centro_estudio) :
                new ObjectParameter("centro_estudio", typeof(string));
    
            var correo_mecParameter = correo_mec != null ?
                new ObjectParameter("correo_mec", correo_mec) :
                new ObjectParameter("correo_mec", typeof(string));
    
            var usu_ult_modParameter = usu_ult_mod != null ?
                new ObjectParameter("usu_ult_mod", usu_ult_mod) :
                new ObjectParameter("usu_ult_mod", typeof(string));
    
            var est_mecParameter = est_mec.HasValue ?
                new ObjectParameter("est_mec", est_mec) :
                new ObjectParameter("est_mec", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarMecanico", idmecParameter, cod_ubigeoParameter, nom_mecParameter, ape_mecParameter, doc_idenParameter, dir_mecanicoParameter, fech_ingresoParameter, tel_mecParameter, fec_nacParameter, sexoParameter, espe_mecParameter, centro_estudioParameter, correo_mecParameter, usu_ult_modParameter, est_mecParameter);
        }
    
        public virtual int usp_EliminarMecanico(string idmec)
        {
            var idmecParameter = idmec != null ?
                new ObjectParameter("idmec", idmec) :
                new ObjectParameter("idmec", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarMecanico", idmecParameter);
        }
    
        public virtual int usp_InsertarMecanico(string cod_ubigeo, string nom_mec, string ape_mec, string doc_iden, string dir_mecanico, Nullable<System.DateTime> fech_ingreso, string tel_mec, Nullable<System.DateTime> fec_nac, string sexo, string espe_mec, string centros_Estudios, string correo_mec, string usu_registro, Nullable<int> est_mec)
        {
            var cod_ubigeoParameter = cod_ubigeo != null ?
                new ObjectParameter("cod_ubigeo", cod_ubigeo) :
                new ObjectParameter("cod_ubigeo", typeof(string));
    
            var nom_mecParameter = nom_mec != null ?
                new ObjectParameter("nom_mec", nom_mec) :
                new ObjectParameter("nom_mec", typeof(string));
    
            var ape_mecParameter = ape_mec != null ?
                new ObjectParameter("ape_mec", ape_mec) :
                new ObjectParameter("ape_mec", typeof(string));
    
            var doc_idenParameter = doc_iden != null ?
                new ObjectParameter("doc_iden", doc_iden) :
                new ObjectParameter("doc_iden", typeof(string));
    
            var dir_mecanicoParameter = dir_mecanico != null ?
                new ObjectParameter("dir_mecanico", dir_mecanico) :
                new ObjectParameter("dir_mecanico", typeof(string));
    
            var fech_ingresoParameter = fech_ingreso.HasValue ?
                new ObjectParameter("fech_ingreso", fech_ingreso) :
                new ObjectParameter("fech_ingreso", typeof(System.DateTime));
    
            var tel_mecParameter = tel_mec != null ?
                new ObjectParameter("tel_mec", tel_mec) :
                new ObjectParameter("tel_mec", typeof(string));
    
            var fec_nacParameter = fec_nac.HasValue ?
                new ObjectParameter("fec_nac", fec_nac) :
                new ObjectParameter("fec_nac", typeof(System.DateTime));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("sexo", sexo) :
                new ObjectParameter("sexo", typeof(string));
    
            var espe_mecParameter = espe_mec != null ?
                new ObjectParameter("espe_mec", espe_mec) :
                new ObjectParameter("espe_mec", typeof(string));
    
            var centros_EstudiosParameter = centros_Estudios != null ?
                new ObjectParameter("centros_Estudios", centros_Estudios) :
                new ObjectParameter("centros_Estudios", typeof(string));
    
            var correo_mecParameter = correo_mec != null ?
                new ObjectParameter("correo_mec", correo_mec) :
                new ObjectParameter("correo_mec", typeof(string));
    
            var usu_registroParameter = usu_registro != null ?
                new ObjectParameter("usu_registro", usu_registro) :
                new ObjectParameter("usu_registro", typeof(string));
    
            var est_mecParameter = est_mec.HasValue ?
                new ObjectParameter("est_mec", est_mec) :
                new ObjectParameter("est_mec", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarMecanico", cod_ubigeoParameter, nom_mecParameter, ape_mecParameter, doc_idenParameter, dir_mecanicoParameter, fech_ingresoParameter, tel_mecParameter, fec_nacParameter, sexoParameter, espe_mecParameter, centros_EstudiosParameter, correo_mecParameter, usu_registroParameter, est_mecParameter);
        }
    
        public virtual ObjectResult<usp_ListarMecanico_Result> usp_ListarMecanico()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarMecanico_Result>("usp_ListarMecanico");
        }
    }
}
