//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Mant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Cliente_Aud
    {
        public string idCliente { get; set; }
        public string cod_ubigeo { get; set; }
        public string Nom_cli { get; set; }
        public string Ape_cli { get; set; }
        public string dir_cli { get; set; }
        public string Ruc_Cli { get; set; }
        public string Telf_Cli { get; set; }
        public Nullable<System.DateTime> Fec_Nac_Cli { get; set; }
        public string Correo_Cli { get; set; }
        public string Sexo { get; set; }
        public string Raz_soc_cli { get; set; }
        public string Dni_Cli { get; set; }
        public Nullable<System.DateTime> Registro_Cliente { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public Nullable<int> Est_Cli { get; set; }
        public Nullable<int> TipoCliente { get; set; }
        public string Accion { get; set; }
        public Nullable<System.DateTime> FechaAccion { get; set; }
    }
}
