//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Mant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Vehiculo_Aud
    {
        public string idVehiculo { get; set; }
        public string idCliente { get; set; }
        public Nullable<int> Act_kilom_Veh { get; set; }
        public Nullable<int> Act_Horom_Veh { get; set; }
        public string idMarca { get; set; }
        public Nullable<int> Tipo_Unidad { get; set; }
        public Nullable<System.DateTime> Fec_Ing_Veh { get; set; }
        public string Color { get; set; }
        public Nullable<int> Tipo_Trans { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> Año_Modelo { get; set; }
        public string Modelo_Vehiculo { get; set; }
        public Nullable<System.DateTime> Fec_Registro { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public string Accion { get; set; }
        public Nullable<System.DateTime> FechaAccion { get; set; }
    }
}
