//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenimiento_WCF_MVC.ProxyEstadistica {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteEstadistica", Namespace="http://schemas.datacontract.org/2004/07/WCF_Mant")]
    [System.SerializableAttribute()]
    public partial class ClienteEstadistica : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float TotalMantenimientosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float TotalMantenimientos {
            get {
                return this.TotalMantenimientosField;
            }
            set {
                if ((this.TotalMantenimientosField.Equals(value) != true)) {
                    this.TotalMantenimientosField = value;
                    this.RaisePropertyChanged("TotalMantenimientos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MecanicoEstadistica", Namespace="http://schemas.datacontract.org/2004/07/WCF_Mant")]
    [System.SerializableAttribute()]
    public partial class MecanicoEstadistica : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float TotalMantenimientosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float TotalMantenimientos {
            get {
                return this.TotalMantenimientosField;
            }
            set {
                if ((this.TotalMantenimientosField.Equals(value) != true)) {
                    this.TotalMantenimientosField = value;
                    this.RaisePropertyChanged("TotalMantenimientos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehiculoEstadistica", Namespace="http://schemas.datacontract.org/2004/07/WCF_Mant")]
    [System.SerializableAttribute()]
    public partial class VehiculoEstadistica : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlacaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float TotalMantenimientosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Placa {
            get {
                return this.PlacaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlacaField, value) != true)) {
                    this.PlacaField = value;
                    this.RaisePropertyChanged("Placa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float TotalMantenimientos {
            get {
                return this.TotalMantenimientosField;
            }
            set {
                if ((this.TotalMantenimientosField.Equals(value) != true)) {
                    this.TotalMantenimientosField = value;
                    this.RaisePropertyChanged("TotalMantenimientos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyEstadistica.IServicioEstadistica")]
    public interface IServicioEstadistica {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadistica/RankingClientesAño", ReplyAction="http://tempuri.org/IServicioEstadistica/RankingClientesAñoResponse")]
        Mantenimiento_WCF_MVC.ProxyEstadistica.ClienteEstadistica[] RankingClientesAño(short año, short top);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadistica/RankingClientesAño", ReplyAction="http://tempuri.org/IServicioEstadistica/RankingClientesAñoResponse")]
        System.Threading.Tasks.Task<Mantenimiento_WCF_MVC.ProxyEstadistica.ClienteEstadistica[]> RankingClientesAñoAsync(short año, short top);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadistica/RankingMecanicoMantAño", ReplyAction="http://tempuri.org/IServicioEstadistica/RankingMecanicoMantAñoResponse")]
        Mantenimiento_WCF_MVC.ProxyEstadistica.MecanicoEstadistica[] RankingMecanicoMantAño(short año, short top);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadistica/RankingMecanicoMantAño", ReplyAction="http://tempuri.org/IServicioEstadistica/RankingMecanicoMantAñoResponse")]
        System.Threading.Tasks.Task<Mantenimiento_WCF_MVC.ProxyEstadistica.MecanicoEstadistica[]> RankingMecanicoMantAñoAsync(short año, short top);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadistica/RankingVehiculoMantAño", ReplyAction="http://tempuri.org/IServicioEstadistica/RankingVehiculoMantAñoResponse")]
        Mantenimiento_WCF_MVC.ProxyEstadistica.VehiculoEstadistica[] RankingVehiculoMantAño(short año, short top);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadistica/RankingVehiculoMantAño", ReplyAction="http://tempuri.org/IServicioEstadistica/RankingVehiculoMantAñoResponse")]
        System.Threading.Tasks.Task<Mantenimiento_WCF_MVC.ProxyEstadistica.VehiculoEstadistica[]> RankingVehiculoMantAñoAsync(short año, short top);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioEstadisticaChannel : Mantenimiento_WCF_MVC.ProxyEstadistica.IServicioEstadistica, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioEstadisticaClient : System.ServiceModel.ClientBase<Mantenimiento_WCF_MVC.ProxyEstadistica.IServicioEstadistica>, Mantenimiento_WCF_MVC.ProxyEstadistica.IServicioEstadistica {
        
        public ServicioEstadisticaClient() {
        }
        
        public ServicioEstadisticaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioEstadisticaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEstadisticaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEstadisticaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Mantenimiento_WCF_MVC.ProxyEstadistica.ClienteEstadistica[] RankingClientesAño(short año, short top) {
            return base.Channel.RankingClientesAño(año, top);
        }
        
        public System.Threading.Tasks.Task<Mantenimiento_WCF_MVC.ProxyEstadistica.ClienteEstadistica[]> RankingClientesAñoAsync(short año, short top) {
            return base.Channel.RankingClientesAñoAsync(año, top);
        }
        
        public Mantenimiento_WCF_MVC.ProxyEstadistica.MecanicoEstadistica[] RankingMecanicoMantAño(short año, short top) {
            return base.Channel.RankingMecanicoMantAño(año, top);
        }
        
        public System.Threading.Tasks.Task<Mantenimiento_WCF_MVC.ProxyEstadistica.MecanicoEstadistica[]> RankingMecanicoMantAñoAsync(short año, short top) {
            return base.Channel.RankingMecanicoMantAñoAsync(año, top);
        }
        
        public Mantenimiento_WCF_MVC.ProxyEstadistica.VehiculoEstadistica[] RankingVehiculoMantAño(short año, short top) {
            return base.Channel.RankingVehiculoMantAño(año, top);
        }
        
        public System.Threading.Tasks.Task<Mantenimiento_WCF_MVC.ProxyEstadistica.VehiculoEstadistica[]> RankingVehiculoMantAñoAsync(short año, short top) {
            return base.Channel.RankingVehiculoMantAñoAsync(año, top);
        }
    }
}
