//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyRank
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteEstadistica", Namespace="http://schemas.datacontract.org/2004/07/WCF_Mant")]
    public partial class ClienteEstadistica : object
    {
        
        private string NombresField;
        
        private float TotalMantenimientosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float TotalMantenimientos
        {
            get
            {
                return this.TotalMantenimientosField;
            }
            set
            {
                this.TotalMantenimientosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MecanicoEstadistica", Namespace="http://schemas.datacontract.org/2004/07/WCF_Mant")]
    public partial class MecanicoEstadistica : object
    {
        
        private string NombresField;
        
        private float TotalMantenimientosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float TotalMantenimientos
        {
            get
            {
                return this.TotalMantenimientosField;
            }
            set
            {
                this.TotalMantenimientosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehiculoEstadistica", Namespace="http://schemas.datacontract.org/2004/07/WCF_Mant")]
    public partial class VehiculoEstadistica : object
    {
        
        private string PlacaField;
        
        private float TotalMantenimientosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Placa
        {
            get
            {
                return this.PlacaField;
            }
            set
            {
                this.PlacaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float TotalMantenimientos
        {
            get
            {
                return this.TotalMantenimientosField;
            }
            set
            {
                this.TotalMantenimientosField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyRank.IServicioEstadistica")]
    public interface IServicioEstadistica
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadistica/RankingClientesAño", ReplyAction="http://tempuri.org/IServicioEstadistica/RankingClientesAñoResponse")]
        System.Collections.Generic.List<ProxyRank.ClienteEstadistica> RankingClientesAño(short año, short top);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadistica/RankingClientesAño", ReplyAction="http://tempuri.org/IServicioEstadistica/RankingClientesAñoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyRank.ClienteEstadistica>> RankingClientesAñoAsync(short año, short top);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadistica/RankingMecanicoMantAño", ReplyAction="http://tempuri.org/IServicioEstadistica/RankingMecanicoMantAñoResponse")]
        System.Collections.Generic.List<ProxyRank.MecanicoEstadistica> RankingMecanicoMantAño(short año, short top);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadistica/RankingMecanicoMantAño", ReplyAction="http://tempuri.org/IServicioEstadistica/RankingMecanicoMantAñoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyRank.MecanicoEstadistica>> RankingMecanicoMantAñoAsync(short año, short top);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadistica/RankingVehiculoMantAño", ReplyAction="http://tempuri.org/IServicioEstadistica/RankingVehiculoMantAñoResponse")]
        System.Collections.Generic.List<ProxyRank.VehiculoEstadistica> RankingVehiculoMantAño(short año, short top);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadistica/RankingVehiculoMantAño", ReplyAction="http://tempuri.org/IServicioEstadistica/RankingVehiculoMantAñoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyRank.VehiculoEstadistica>> RankingVehiculoMantAñoAsync(short año, short top);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServicioEstadisticaChannel : ProxyRank.IServicioEstadistica, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServicioEstadisticaClient : System.ServiceModel.ClientBase<ProxyRank.IServicioEstadistica>, ProxyRank.IServicioEstadistica
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioEstadisticaClient() : 
                base(ServicioEstadisticaClient.GetDefaultBinding(), ServicioEstadisticaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioEstadistica.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEstadisticaClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioEstadisticaClient.GetBindingForEndpoint(endpointConfiguration), ServicioEstadisticaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEstadisticaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioEstadisticaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEstadisticaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioEstadisticaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEstadisticaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ProxyRank.ClienteEstadistica> RankingClientesAño(short año, short top)
        {
            return base.Channel.RankingClientesAño(año, top);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyRank.ClienteEstadistica>> RankingClientesAñoAsync(short año, short top)
        {
            return base.Channel.RankingClientesAñoAsync(año, top);
        }
        
        public System.Collections.Generic.List<ProxyRank.MecanicoEstadistica> RankingMecanicoMantAño(short año, short top)
        {
            return base.Channel.RankingMecanicoMantAño(año, top);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyRank.MecanicoEstadistica>> RankingMecanicoMantAñoAsync(short año, short top)
        {
            return base.Channel.RankingMecanicoMantAñoAsync(año, top);
        }
        
        public System.Collections.Generic.List<ProxyRank.VehiculoEstadistica> RankingVehiculoMantAño(short año, short top)
        {
            return base.Channel.RankingVehiculoMantAño(año, top);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyRank.VehiculoEstadistica>> RankingVehiculoMantAñoAsync(short año, short top)
        {
            return base.Channel.RankingVehiculoMantAñoAsync(año, top);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioEstadistica))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioEstadistica))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_Mant/ServicioEstadistica/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioEstadisticaClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioEstadistica);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioEstadisticaClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioEstadistica);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioEstadistica,
        }
    }
}
