//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyMecanico
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MecanicoFecDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Mant")]
    public partial class MecanicoFecDC : object
    {
        
        private string Ape_cliField;
        
        private string Ape_mecField;
        
        private float Est_MecField;
        
        private string EstadoField;
        
        private System.DateTime Fec_Mant_FinField;
        
        private System.DateTime Fec_Mant_InicField;
        
        private System.DateTime Fech_IngresoField;
        
        private string Nom_cliField;
        
        private string Nom_mecField;
        
        private string Raz_soc_cliField;
        
        private string Ruc_CliField;
        
        private string TipoUnidadField;
        
        private float Tipo_unidadField;
        
        private string idMantenimientoField;
        
        private string idMecanicoField;
        
        private string idVehiculoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_cli
        {
            get
            {
                return this.Ape_cliField;
            }
            set
            {
                this.Ape_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_mec
        {
            get
            {
                return this.Ape_mecField;
            }
            set
            {
                this.Ape_mecField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Est_Mec
        {
            get
            {
                return this.Est_MecField;
            }
            set
            {
                this.Est_MecField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Mant_Fin
        {
            get
            {
                return this.Fec_Mant_FinField;
            }
            set
            {
                this.Fec_Mant_FinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Mant_Inic
        {
            get
            {
                return this.Fec_Mant_InicField;
            }
            set
            {
                this.Fec_Mant_InicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fech_Ingreso
        {
            get
            {
                return this.Fech_IngresoField;
            }
            set
            {
                this.Fech_IngresoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_cli
        {
            get
            {
                return this.Nom_cliField;
            }
            set
            {
                this.Nom_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_mec
        {
            get
            {
                return this.Nom_mecField;
            }
            set
            {
                this.Nom_mecField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Raz_soc_cli
        {
            get
            {
                return this.Raz_soc_cliField;
            }
            set
            {
                this.Raz_soc_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruc_Cli
        {
            get
            {
                return this.Ruc_CliField;
            }
            set
            {
                this.Ruc_CliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoUnidad
        {
            get
            {
                return this.TipoUnidadField;
            }
            set
            {
                this.TipoUnidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Tipo_unidad
        {
            get
            {
                return this.Tipo_unidadField;
            }
            set
            {
                this.Tipo_unidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idMantenimiento
        {
            get
            {
                return this.idMantenimientoField;
            }
            set
            {
                this.idMantenimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idMecanico
        {
            get
            {
                return this.idMecanicoField;
            }
            set
            {
                this.idMecanicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idVehiculo
        {
            get
            {
                return this.idVehiculoField;
            }
            set
            {
                this.idVehiculoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MecanicoDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Mant")]
    public partial class MecanicoDC : object
    {
        
        private string Ape_mecField;
        
        private string Centro_EstudiosField;
        
        private string Correo_MecField;
        
        private string Doc_IdenField;
        
        private string Espe_MecField;
        
        private short Est_MecField;
        
        private string EstadoField;
        
        private System.DateTime Fech_IngresoField;
        
        private System.DateTime Fech_NacField;
        
        private System.DateTime Fech_RegistroField;
        
        private System.DateTime Fech_Ult_ModField;
        
        private string Nom_mecField;
        
        private string SexoField;
        
        private string Telf_MecField;
        
        private string Usu_RegistroField;
        
        private string Usu_Ult_ModField;
        
        private string cod_ubigeoField;
        
        private string dir_mecanicoField;
        
        private string idMecanicoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_mec
        {
            get
            {
                return this.Ape_mecField;
            }
            set
            {
                this.Ape_mecField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Centro_Estudios
        {
            get
            {
                return this.Centro_EstudiosField;
            }
            set
            {
                this.Centro_EstudiosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo_Mec
        {
            get
            {
                return this.Correo_MecField;
            }
            set
            {
                this.Correo_MecField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Doc_Iden
        {
            get
            {
                return this.Doc_IdenField;
            }
            set
            {
                this.Doc_IdenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Espe_Mec
        {
            get
            {
                return this.Espe_MecField;
            }
            set
            {
                this.Espe_MecField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Est_Mec
        {
            get
            {
                return this.Est_MecField;
            }
            set
            {
                this.Est_MecField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fech_Ingreso
        {
            get
            {
                return this.Fech_IngresoField;
            }
            set
            {
                this.Fech_IngresoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fech_Nac
        {
            get
            {
                return this.Fech_NacField;
            }
            set
            {
                this.Fech_NacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fech_Registro
        {
            get
            {
                return this.Fech_RegistroField;
            }
            set
            {
                this.Fech_RegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fech_Ult_Mod
        {
            get
            {
                return this.Fech_Ult_ModField;
            }
            set
            {
                this.Fech_Ult_ModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_mec
        {
            get
            {
                return this.Nom_mecField;
            }
            set
            {
                this.Nom_mecField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo
        {
            get
            {
                return this.SexoField;
            }
            set
            {
                this.SexoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telf_Mec
        {
            get
            {
                return this.Telf_MecField;
            }
            set
            {
                this.Telf_MecField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro
        {
            get
            {
                return this.Usu_RegistroField;
            }
            set
            {
                this.Usu_RegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod
        {
            get
            {
                return this.Usu_Ult_ModField;
            }
            set
            {
                this.Usu_Ult_ModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_ubigeo
        {
            get
            {
                return this.cod_ubigeoField;
            }
            set
            {
                this.cod_ubigeoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dir_mecanico
        {
            get
            {
                return this.dir_mecanicoField;
            }
            set
            {
                this.dir_mecanicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idMecanico
        {
            get
            {
                return this.idMecanicoField;
            }
            set
            {
                this.idMecanicoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyMecanico.IMecanico")]
    public interface IMecanico
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMecanico/ListarMecanicoFechas", ReplyAction="http://tempuri.org/IMecanico/ListarMecanicoFechasResponse")]
        System.Collections.Generic.List<ProxyMecanico.MecanicoFecDC> ListarMecanicoFechas(string strMecanico, System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMecanico/ListarMecanicoFechas", ReplyAction="http://tempuri.org/IMecanico/ListarMecanicoFechasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyMecanico.MecanicoFecDC>> ListarMecanicoFechasAsync(string strMecanico, System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMecanico/ListarMecanico", ReplyAction="http://tempuri.org/IMecanico/ListarMecanicoResponse")]
        System.Collections.Generic.List<ProxyMecanico.MecanicoDC> ListarMecanico();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMecanico/ListarMecanico", ReplyAction="http://tempuri.org/IMecanico/ListarMecanicoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyMecanico.MecanicoDC>> ListarMecanicoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMecanico/InsertarMecanico", ReplyAction="http://tempuri.org/IMecanico/InsertarMecanicoResponse")]
        bool InsertarMecanico(ProxyMecanico.MecanicoDC objMecanicoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMecanico/InsertarMecanico", ReplyAction="http://tempuri.org/IMecanico/InsertarMecanicoResponse")]
        System.Threading.Tasks.Task<bool> InsertarMecanicoAsync(ProxyMecanico.MecanicoDC objMecanicoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMecanico/ActualizarMecanico", ReplyAction="http://tempuri.org/IMecanico/ActualizarMecanicoResponse")]
        bool ActualizarMecanico(ProxyMecanico.MecanicoDC objMecanicoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMecanico/ActualizarMecanico", ReplyAction="http://tempuri.org/IMecanico/ActualizarMecanicoResponse")]
        System.Threading.Tasks.Task<bool> ActualizarMecanicoAsync(ProxyMecanico.MecanicoDC objMecanicoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMecanico/EliminarMecanico", ReplyAction="http://tempuri.org/IMecanico/EliminarMecanicoResponse")]
        bool EliminarMecanico(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMecanico/EliminarMecanico", ReplyAction="http://tempuri.org/IMecanico/EliminarMecanicoResponse")]
        System.Threading.Tasks.Task<bool> EliminarMecanicoAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMecanico/ConsultarMecanico", ReplyAction="http://tempuri.org/IMecanico/ConsultarMecanicoResponse")]
        ProxyMecanico.MecanicoDC ConsultarMecanico(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMecanico/ConsultarMecanico", ReplyAction="http://tempuri.org/IMecanico/ConsultarMecanicoResponse")]
        System.Threading.Tasks.Task<ProxyMecanico.MecanicoDC> ConsultarMecanicoAsync(string strCodigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IMecanicoChannel : ProxyMecanico.IMecanico, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class MecanicoClient : System.ServiceModel.ClientBase<ProxyMecanico.IMecanico>, ProxyMecanico.IMecanico
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MecanicoClient() : 
                base(MecanicoClient.GetDefaultBinding(), MecanicoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMecanico.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MecanicoClient(EndpointConfiguration endpointConfiguration) : 
                base(MecanicoClient.GetBindingForEndpoint(endpointConfiguration), MecanicoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MecanicoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MecanicoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MecanicoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MecanicoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MecanicoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ProxyMecanico.MecanicoFecDC> ListarMecanicoFechas(string strMecanico, System.DateTime fecini, System.DateTime fecfin)
        {
            return base.Channel.ListarMecanicoFechas(strMecanico, fecini, fecfin);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyMecanico.MecanicoFecDC>> ListarMecanicoFechasAsync(string strMecanico, System.DateTime fecini, System.DateTime fecfin)
        {
            return base.Channel.ListarMecanicoFechasAsync(strMecanico, fecini, fecfin);
        }
        
        public System.Collections.Generic.List<ProxyMecanico.MecanicoDC> ListarMecanico()
        {
            return base.Channel.ListarMecanico();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyMecanico.MecanicoDC>> ListarMecanicoAsync()
        {
            return base.Channel.ListarMecanicoAsync();
        }
        
        public bool InsertarMecanico(ProxyMecanico.MecanicoDC objMecanicoDC)
        {
            return base.Channel.InsertarMecanico(objMecanicoDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarMecanicoAsync(ProxyMecanico.MecanicoDC objMecanicoDC)
        {
            return base.Channel.InsertarMecanicoAsync(objMecanicoDC);
        }
        
        public bool ActualizarMecanico(ProxyMecanico.MecanicoDC objMecanicoDC)
        {
            return base.Channel.ActualizarMecanico(objMecanicoDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarMecanicoAsync(ProxyMecanico.MecanicoDC objMecanicoDC)
        {
            return base.Channel.ActualizarMecanicoAsync(objMecanicoDC);
        }
        
        public bool EliminarMecanico(string strCodigo)
        {
            return base.Channel.EliminarMecanico(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarMecanicoAsync(string strCodigo)
        {
            return base.Channel.EliminarMecanicoAsync(strCodigo);
        }
        
        public ProxyMecanico.MecanicoDC ConsultarMecanico(string strCodigo)
        {
            return base.Channel.ConsultarMecanico(strCodigo);
        }
        
        public System.Threading.Tasks.Task<ProxyMecanico.MecanicoDC> ConsultarMecanicoAsync(string strCodigo)
        {
            return base.Channel.ConsultarMecanicoAsync(strCodigo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMecanico))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMecanico))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_Mant/Mecanico/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MecanicoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMecanico);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MecanicoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMecanico);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMecanico,
        }
    }
}
