//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyCliente
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Mant")]
    public partial class ClienteDC : object
    {
        
        private string Ape_cliField;
        
        private string Correo_CliField;
        
        private string Dni_CliField;
        
        private float Est_CliField;
        
        private string EstadoClienteField;
        
        private System.DateTime Fec_Nac_CliField;
        
        private System.DateTime Fec_Reg_CliField;
        
        private System.DateTime Fec_Ult_ModField;
        
        private string Nom_cliField;
        
        private string Raz_soc_cliField;
        
        private string Ruc_CliField;
        
        private string SexoField;
        
        private string Telf_CliField;
        
        private float TipoClienteField;
        
        private string Usu_RegistroField;
        
        private string Usu_Ult_ModField;
        
        private string cod_ubigeoField;
        
        private string dir_cliField;
        
        private string idClienteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_cli
        {
            get
            {
                return this.Ape_cliField;
            }
            set
            {
                this.Ape_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo_Cli
        {
            get
            {
                return this.Correo_CliField;
            }
            set
            {
                this.Correo_CliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni_Cli
        {
            get
            {
                return this.Dni_CliField;
            }
            set
            {
                this.Dni_CliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Est_Cli
        {
            get
            {
                return this.Est_CliField;
            }
            set
            {
                this.Est_CliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoCliente
        {
            get
            {
                return this.EstadoClienteField;
            }
            set
            {
                this.EstadoClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Nac_Cli
        {
            get
            {
                return this.Fec_Nac_CliField;
            }
            set
            {
                this.Fec_Nac_CliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Reg_Cli
        {
            get
            {
                return this.Fec_Reg_CliField;
            }
            set
            {
                this.Fec_Reg_CliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod
        {
            get
            {
                return this.Fec_Ult_ModField;
            }
            set
            {
                this.Fec_Ult_ModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_cli
        {
            get
            {
                return this.Nom_cliField;
            }
            set
            {
                this.Nom_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Raz_soc_cli
        {
            get
            {
                return this.Raz_soc_cliField;
            }
            set
            {
                this.Raz_soc_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruc_Cli
        {
            get
            {
                return this.Ruc_CliField;
            }
            set
            {
                this.Ruc_CliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo
        {
            get
            {
                return this.SexoField;
            }
            set
            {
                this.SexoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telf_Cli
        {
            get
            {
                return this.Telf_CliField;
            }
            set
            {
                this.Telf_CliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float TipoCliente
        {
            get
            {
                return this.TipoClienteField;
            }
            set
            {
                this.TipoClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro
        {
            get
            {
                return this.Usu_RegistroField;
            }
            set
            {
                this.Usu_RegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod
        {
            get
            {
                return this.Usu_Ult_ModField;
            }
            set
            {
                this.Usu_Ult_ModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_ubigeo
        {
            get
            {
                return this.cod_ubigeoField;
            }
            set
            {
                this.cod_ubigeoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dir_cli
        {
            get
            {
                return this.dir_cliField;
            }
            set
            {
                this.dir_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idCliente
        {
            get
            {
                return this.idClienteField;
            }
            set
            {
                this.idClienteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteFecDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Mant")]
    public partial class ClienteFecDC : object
    {
        
        private string Ape_cliField;
        
        private string Ape_mecField;
        
        private string Dni_CliField;
        
        private float Est_CliField;
        
        private float Est_MecField;
        
        private string EstadoClienteField;
        
        private string EstadoMecanicoField;
        
        private System.DateTime Fec_Mant_FinField;
        
        private System.DateTime Fec_Mant_InicField;
        
        private string Nom_cliField;
        
        private string Nom_mecField;
        
        private string Raz_soc_cliField;
        
        private string Ruc_CliField;
        
        private string TipoUnidadField;
        
        private float Tipo_UnidadField;
        
        private string idClienteField;
        
        private string idMarcaField;
        
        private string idVehiculoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_cli
        {
            get
            {
                return this.Ape_cliField;
            }
            set
            {
                this.Ape_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_mec
        {
            get
            {
                return this.Ape_mecField;
            }
            set
            {
                this.Ape_mecField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni_Cli
        {
            get
            {
                return this.Dni_CliField;
            }
            set
            {
                this.Dni_CliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Est_Cli
        {
            get
            {
                return this.Est_CliField;
            }
            set
            {
                this.Est_CliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Est_Mec
        {
            get
            {
                return this.Est_MecField;
            }
            set
            {
                this.Est_MecField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoCliente
        {
            get
            {
                return this.EstadoClienteField;
            }
            set
            {
                this.EstadoClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoMecanico
        {
            get
            {
                return this.EstadoMecanicoField;
            }
            set
            {
                this.EstadoMecanicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Mant_Fin
        {
            get
            {
                return this.Fec_Mant_FinField;
            }
            set
            {
                this.Fec_Mant_FinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Mant_Inic
        {
            get
            {
                return this.Fec_Mant_InicField;
            }
            set
            {
                this.Fec_Mant_InicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_cli
        {
            get
            {
                return this.Nom_cliField;
            }
            set
            {
                this.Nom_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_mec
        {
            get
            {
                return this.Nom_mecField;
            }
            set
            {
                this.Nom_mecField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Raz_soc_cli
        {
            get
            {
                return this.Raz_soc_cliField;
            }
            set
            {
                this.Raz_soc_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruc_Cli
        {
            get
            {
                return this.Ruc_CliField;
            }
            set
            {
                this.Ruc_CliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoUnidad
        {
            get
            {
                return this.TipoUnidadField;
            }
            set
            {
                this.TipoUnidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Tipo_Unidad
        {
            get
            {
                return this.Tipo_UnidadField;
            }
            set
            {
                this.Tipo_UnidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idCliente
        {
            get
            {
                return this.idClienteField;
            }
            set
            {
                this.idClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idMarca
        {
            get
            {
                return this.idMarcaField;
            }
            set
            {
                this.idMarcaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idVehiculo
        {
            get
            {
                return this.idVehiculoField;
            }
            set
            {
                this.idVehiculoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCliente.IServicioCliente")]
    public interface IServicioCliente
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ConsultarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ConsultarClienteResponse")]
        ProxyCliente.ClienteDC ConsultarCliente(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ConsultarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ConsultarClienteResponse")]
        System.Threading.Tasks.Task<ProxyCliente.ClienteDC> ConsultarClienteAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ListarClienteFechas", ReplyAction="http://tempuri.org/IServicioCliente/ListarClienteFechasResponse")]
        System.Collections.Generic.List<ProxyCliente.ClienteFecDC> ListarClienteFechas(string strCliente, System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ListarClienteFechas", ReplyAction="http://tempuri.org/IServicioCliente/ListarClienteFechasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyCliente.ClienteFecDC>> ListarClienteFechasAsync(string strCliente, System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ListarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ListarClienteResponse")]
        System.Collections.Generic.List<ProxyCliente.ClienteDC> ListarCliente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ListarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ListarClienteResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyCliente.ClienteDC>> ListarClienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/InsertarCliente", ReplyAction="http://tempuri.org/IServicioCliente/InsertarClienteResponse")]
        bool InsertarCliente(ProxyCliente.ClienteDC objClienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/InsertarCliente", ReplyAction="http://tempuri.org/IServicioCliente/InsertarClienteResponse")]
        System.Threading.Tasks.Task<bool> InsertarClienteAsync(ProxyCliente.ClienteDC objClienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ActualizarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ActualizarClienteResponse")]
        bool ActualizarCliente(ProxyCliente.ClienteDC objClienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ActualizarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ActualizarClienteResponse")]
        System.Threading.Tasks.Task<bool> ActualizarClienteAsync(ProxyCliente.ClienteDC objClienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/EliminarCliente", ReplyAction="http://tempuri.org/IServicioCliente/EliminarClienteResponse")]
        bool EliminarCliente(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/EliminarCliente", ReplyAction="http://tempuri.org/IServicioCliente/EliminarClienteResponse")]
        System.Threading.Tasks.Task<bool> EliminarClienteAsync(string strCodigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServicioClienteChannel : ProxyCliente.IServicioCliente, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServicioClienteClient : System.ServiceModel.ClientBase<ProxyCliente.IServicioCliente>, ProxyCliente.IServicioCliente
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioClienteClient() : 
                base(ServicioClienteClient.GetDefaultBinding(), ServicioClienteClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioCliente.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioClienteClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioClienteClient.GetBindingForEndpoint(endpointConfiguration), ServicioClienteClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioClienteClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioClienteClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioClienteClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioClienteClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ProxyCliente.ClienteDC ConsultarCliente(string strCodigo)
        {
            return base.Channel.ConsultarCliente(strCodigo);
        }
        
        public System.Threading.Tasks.Task<ProxyCliente.ClienteDC> ConsultarClienteAsync(string strCodigo)
        {
            return base.Channel.ConsultarClienteAsync(strCodigo);
        }
        
        public System.Collections.Generic.List<ProxyCliente.ClienteFecDC> ListarClienteFechas(string strCliente, System.DateTime fecini, System.DateTime fecfin)
        {
            return base.Channel.ListarClienteFechas(strCliente, fecini, fecfin);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyCliente.ClienteFecDC>> ListarClienteFechasAsync(string strCliente, System.DateTime fecini, System.DateTime fecfin)
        {
            return base.Channel.ListarClienteFechasAsync(strCliente, fecini, fecfin);
        }
        
        public System.Collections.Generic.List<ProxyCliente.ClienteDC> ListarCliente()
        {
            return base.Channel.ListarCliente();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyCliente.ClienteDC>> ListarClienteAsync()
        {
            return base.Channel.ListarClienteAsync();
        }
        
        public bool InsertarCliente(ProxyCliente.ClienteDC objClienteDC)
        {
            return base.Channel.InsertarCliente(objClienteDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarClienteAsync(ProxyCliente.ClienteDC objClienteDC)
        {
            return base.Channel.InsertarClienteAsync(objClienteDC);
        }
        
        public bool ActualizarCliente(ProxyCliente.ClienteDC objClienteDC)
        {
            return base.Channel.ActualizarCliente(objClienteDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarClienteAsync(ProxyCliente.ClienteDC objClienteDC)
        {
            return base.Channel.ActualizarClienteAsync(objClienteDC);
        }
        
        public bool EliminarCliente(string strCodigo)
        {
            return base.Channel.EliminarCliente(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarClienteAsync(string strCodigo)
        {
            return base.Channel.EliminarClienteAsync(strCodigo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioCliente))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioCliente))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_Mant/ServicioCliente/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioClienteClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioCliente);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioClienteClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioCliente);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioCliente,
        }
    }
}
