//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyVehiculo
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehiculoDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Mant")]
    public partial class VehiculoDC : object
    {
        
        private string Ape_cliField;
        
        private string Ape_mecField;
        
        private System.DateTime Fec_Mant_FinField;
        
        private System.DateTime Fec_Mant_InicField;
        
        private string Nom_cliField;
        
        private string Nom_mecField;
        
        private string TipoMantenimientoField;
        
        private string TipoTransmisionField;
        
        private string TipoUnidadField;
        
        private float Tipo_TransField;
        
        private float Tipo_UnidadField;
        
        private string idMarcaField;
        
        private string idMecanicoField;
        
        private string idVehiculoField;
        
        private string modeloField;
        
        private float tipo_mantenimientoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_cli
        {
            get
            {
                return this.Ape_cliField;
            }
            set
            {
                this.Ape_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_mec
        {
            get
            {
                return this.Ape_mecField;
            }
            set
            {
                this.Ape_mecField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Mant_Fin
        {
            get
            {
                return this.Fec_Mant_FinField;
            }
            set
            {
                this.Fec_Mant_FinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Mant_Inic
        {
            get
            {
                return this.Fec_Mant_InicField;
            }
            set
            {
                this.Fec_Mant_InicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_cli
        {
            get
            {
                return this.Nom_cliField;
            }
            set
            {
                this.Nom_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_mec
        {
            get
            {
                return this.Nom_mecField;
            }
            set
            {
                this.Nom_mecField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoMantenimiento
        {
            get
            {
                return this.TipoMantenimientoField;
            }
            set
            {
                this.TipoMantenimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoTransmision
        {
            get
            {
                return this.TipoTransmisionField;
            }
            set
            {
                this.TipoTransmisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoUnidad
        {
            get
            {
                return this.TipoUnidadField;
            }
            set
            {
                this.TipoUnidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Tipo_Trans
        {
            get
            {
                return this.Tipo_TransField;
            }
            set
            {
                this.Tipo_TransField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Tipo_Unidad
        {
            get
            {
                return this.Tipo_UnidadField;
            }
            set
            {
                this.Tipo_UnidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idMarca
        {
            get
            {
                return this.idMarcaField;
            }
            set
            {
                this.idMarcaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idMecanico
        {
            get
            {
                return this.idMecanicoField;
            }
            set
            {
                this.idMecanicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idVehiculo
        {
            get
            {
                return this.idVehiculoField;
            }
            set
            {
                this.idVehiculoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string modelo
        {
            get
            {
                return this.modeloField;
            }
            set
            {
                this.modeloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float tipo_mantenimiento
        {
            get
            {
                return this.tipo_mantenimientoField;
            }
            set
            {
                this.tipo_mantenimientoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyVehiculo.IServicioVehiculos")]
    public interface IServicioVehiculos
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVehiculos/ListarVehiculosFechas", ReplyAction="http://tempuri.org/IServicioVehiculos/ListarVehiculosFechasResponse")]
        System.Collections.Generic.List<ProxyVehiculo.VehiculoDC> ListarVehiculosFechas(string strVehiculo, System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVehiculos/ListarVehiculosFechas", ReplyAction="http://tempuri.org/IServicioVehiculos/ListarVehiculosFechasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyVehiculo.VehiculoDC>> ListarVehiculosFechasAsync(string strVehiculo, System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVehiculos/ConsultarVehiculos", ReplyAction="http://tempuri.org/IServicioVehiculos/ConsultarVehiculosResponse")]
        ProxyVehiculo.VehiculoDC ConsultarVehiculos(string strVehiculo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVehiculos/ConsultarVehiculos", ReplyAction="http://tempuri.org/IServicioVehiculos/ConsultarVehiculosResponse")]
        System.Threading.Tasks.Task<ProxyVehiculo.VehiculoDC> ConsultarVehiculosAsync(string strVehiculo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServicioVehiculosChannel : ProxyVehiculo.IServicioVehiculos, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServicioVehiculosClient : System.ServiceModel.ClientBase<ProxyVehiculo.IServicioVehiculos>, ProxyVehiculo.IServicioVehiculos
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioVehiculosClient() : 
                base(ServicioVehiculosClient.GetDefaultBinding(), ServicioVehiculosClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioVehiculos.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioVehiculosClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioVehiculosClient.GetBindingForEndpoint(endpointConfiguration), ServicioVehiculosClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioVehiculosClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioVehiculosClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioVehiculosClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioVehiculosClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioVehiculosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ProxyVehiculo.VehiculoDC> ListarVehiculosFechas(string strVehiculo, System.DateTime fecini, System.DateTime fecfin)
        {
            return base.Channel.ListarVehiculosFechas(strVehiculo, fecini, fecfin);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyVehiculo.VehiculoDC>> ListarVehiculosFechasAsync(string strVehiculo, System.DateTime fecini, System.DateTime fecfin)
        {
            return base.Channel.ListarVehiculosFechasAsync(strVehiculo, fecini, fecfin);
        }
        
        public ProxyVehiculo.VehiculoDC ConsultarVehiculos(string strVehiculo)
        {
            return base.Channel.ConsultarVehiculos(strVehiculo);
        }
        
        public System.Threading.Tasks.Task<ProxyVehiculo.VehiculoDC> ConsultarVehiculosAsync(string strVehiculo)
        {
            return base.Channel.ConsultarVehiculosAsync(strVehiculo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioVehiculos))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioVehiculos))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_Mant/ServicioVehiculos/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioVehiculosClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioVehiculos);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioVehiculosClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioVehiculos);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioVehiculos,
        }
    }
}
