//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenimiento_WCF_MVC.ProxyVehiculos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehiculoDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Mant")]
    [System.SerializableAttribute()]
    public partial class VehiculoDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ape_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ape_mecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_Mant_FinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_Mant_InicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_mecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoMantenimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoTransmisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoUnidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float Tipo_TransField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float Tipo_UnidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idMarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idMecanicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idVehiculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float tipo_mantenimientoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_cli {
            get {
                return this.Ape_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Ape_cliField, value) != true)) {
                    this.Ape_cliField = value;
                    this.RaisePropertyChanged("Ape_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_mec {
            get {
                return this.Ape_mecField;
            }
            set {
                if ((object.ReferenceEquals(this.Ape_mecField, value) != true)) {
                    this.Ape_mecField = value;
                    this.RaisePropertyChanged("Ape_mec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Mant_Fin {
            get {
                return this.Fec_Mant_FinField;
            }
            set {
                if ((this.Fec_Mant_FinField.Equals(value) != true)) {
                    this.Fec_Mant_FinField = value;
                    this.RaisePropertyChanged("Fec_Mant_Fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Mant_Inic {
            get {
                return this.Fec_Mant_InicField;
            }
            set {
                if ((this.Fec_Mant_InicField.Equals(value) != true)) {
                    this.Fec_Mant_InicField = value;
                    this.RaisePropertyChanged("Fec_Mant_Inic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_cli {
            get {
                return this.Nom_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_cliField, value) != true)) {
                    this.Nom_cliField = value;
                    this.RaisePropertyChanged("Nom_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_mec {
            get {
                return this.Nom_mecField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_mecField, value) != true)) {
                    this.Nom_mecField = value;
                    this.RaisePropertyChanged("Nom_mec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoMantenimiento {
            get {
                return this.TipoMantenimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoMantenimientoField, value) != true)) {
                    this.TipoMantenimientoField = value;
                    this.RaisePropertyChanged("TipoMantenimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoTransmision {
            get {
                return this.TipoTransmisionField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoTransmisionField, value) != true)) {
                    this.TipoTransmisionField = value;
                    this.RaisePropertyChanged("TipoTransmision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoUnidad {
            get {
                return this.TipoUnidadField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoUnidadField, value) != true)) {
                    this.TipoUnidadField = value;
                    this.RaisePropertyChanged("TipoUnidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Tipo_Trans {
            get {
                return this.Tipo_TransField;
            }
            set {
                if ((this.Tipo_TransField.Equals(value) != true)) {
                    this.Tipo_TransField = value;
                    this.RaisePropertyChanged("Tipo_Trans");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Tipo_Unidad {
            get {
                return this.Tipo_UnidadField;
            }
            set {
                if ((this.Tipo_UnidadField.Equals(value) != true)) {
                    this.Tipo_UnidadField = value;
                    this.RaisePropertyChanged("Tipo_Unidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idMarca {
            get {
                return this.idMarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.idMarcaField, value) != true)) {
                    this.idMarcaField = value;
                    this.RaisePropertyChanged("idMarca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idMecanico {
            get {
                return this.idMecanicoField;
            }
            set {
                if ((object.ReferenceEquals(this.idMecanicoField, value) != true)) {
                    this.idMecanicoField = value;
                    this.RaisePropertyChanged("idMecanico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idVehiculo {
            get {
                return this.idVehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.idVehiculoField, value) != true)) {
                    this.idVehiculoField = value;
                    this.RaisePropertyChanged("idVehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                if ((object.ReferenceEquals(this.modeloField, value) != true)) {
                    this.modeloField = value;
                    this.RaisePropertyChanged("modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float tipo_mantenimiento {
            get {
                return this.tipo_mantenimientoField;
            }
            set {
                if ((this.tipo_mantenimientoField.Equals(value) != true)) {
                    this.tipo_mantenimientoField = value;
                    this.RaisePropertyChanged("tipo_mantenimiento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyVehiculos.IServicioVehiculos")]
    public interface IServicioVehiculos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVehiculos/ListarVehiculosFechas", ReplyAction="http://tempuri.org/IServicioVehiculos/ListarVehiculosFechasResponse")]
        Mantenimiento_WCF_MVC.ProxyVehiculos.VehiculoDC[] ListarVehiculosFechas(string strVehiculo, System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVehiculos/ListarVehiculosFechas", ReplyAction="http://tempuri.org/IServicioVehiculos/ListarVehiculosFechasResponse")]
        System.Threading.Tasks.Task<Mantenimiento_WCF_MVC.ProxyVehiculos.VehiculoDC[]> ListarVehiculosFechasAsync(string strVehiculo, System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVehiculos/ConsultarVehiculos", ReplyAction="http://tempuri.org/IServicioVehiculos/ConsultarVehiculosResponse")]
        Mantenimiento_WCF_MVC.ProxyVehiculos.VehiculoDC ConsultarVehiculos(string strVehiculo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVehiculos/ConsultarVehiculos", ReplyAction="http://tempuri.org/IServicioVehiculos/ConsultarVehiculosResponse")]
        System.Threading.Tasks.Task<Mantenimiento_WCF_MVC.ProxyVehiculos.VehiculoDC> ConsultarVehiculosAsync(string strVehiculo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioVehiculosChannel : Mantenimiento_WCF_MVC.ProxyVehiculos.IServicioVehiculos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioVehiculosClient : System.ServiceModel.ClientBase<Mantenimiento_WCF_MVC.ProxyVehiculos.IServicioVehiculos>, Mantenimiento_WCF_MVC.ProxyVehiculos.IServicioVehiculos {
        
        public ServicioVehiculosClient() {
        }
        
        public ServicioVehiculosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioVehiculosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioVehiculosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioVehiculosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Mantenimiento_WCF_MVC.ProxyVehiculos.VehiculoDC[] ListarVehiculosFechas(string strVehiculo, System.DateTime fecini, System.DateTime fecfin) {
            return base.Channel.ListarVehiculosFechas(strVehiculo, fecini, fecfin);
        }
        
        public System.Threading.Tasks.Task<Mantenimiento_WCF_MVC.ProxyVehiculos.VehiculoDC[]> ListarVehiculosFechasAsync(string strVehiculo, System.DateTime fecini, System.DateTime fecfin) {
            return base.Channel.ListarVehiculosFechasAsync(strVehiculo, fecini, fecfin);
        }
        
        public Mantenimiento_WCF_MVC.ProxyVehiculos.VehiculoDC ConsultarVehiculos(string strVehiculo) {
            return base.Channel.ConsultarVehiculos(strVehiculo);
        }
        
        public System.Threading.Tasks.Task<Mantenimiento_WCF_MVC.ProxyVehiculos.VehiculoDC> ConsultarVehiculosAsync(string strVehiculo) {
            return base.Channel.ConsultarVehiculosAsync(strVehiculo);
        }
    }
}
