//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenimiento_WCF_MVC.ProxyClientes {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Mant")]
    [System.SerializableAttribute()]
    public partial class ClienteDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ape_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Correo_CliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dni_CliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float Est_CliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_Nac_CliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_Reg_CliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Raz_soc_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ruc_CliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Telf_CliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float TipoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_ubigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dir_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idClienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_cli {
            get {
                return this.Ape_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Ape_cliField, value) != true)) {
                    this.Ape_cliField = value;
                    this.RaisePropertyChanged("Ape_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo_Cli {
            get {
                return this.Correo_CliField;
            }
            set {
                if ((object.ReferenceEquals(this.Correo_CliField, value) != true)) {
                    this.Correo_CliField = value;
                    this.RaisePropertyChanged("Correo_Cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni_Cli {
            get {
                return this.Dni_CliField;
            }
            set {
                if ((object.ReferenceEquals(this.Dni_CliField, value) != true)) {
                    this.Dni_CliField = value;
                    this.RaisePropertyChanged("Dni_Cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Est_Cli {
            get {
                return this.Est_CliField;
            }
            set {
                if ((this.Est_CliField.Equals(value) != true)) {
                    this.Est_CliField = value;
                    this.RaisePropertyChanged("Est_Cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoCliente {
            get {
                return this.EstadoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoClienteField, value) != true)) {
                    this.EstadoClienteField = value;
                    this.RaisePropertyChanged("EstadoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Nac_Cli {
            get {
                return this.Fec_Nac_CliField;
            }
            set {
                if ((this.Fec_Nac_CliField.Equals(value) != true)) {
                    this.Fec_Nac_CliField = value;
                    this.RaisePropertyChanged("Fec_Nac_Cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Reg_Cli {
            get {
                return this.Fec_Reg_CliField;
            }
            set {
                if ((this.Fec_Reg_CliField.Equals(value) != true)) {
                    this.Fec_Reg_CliField = value;
                    this.RaisePropertyChanged("Fec_Reg_Cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod {
            get {
                return this.Fec_Ult_ModField;
            }
            set {
                if ((this.Fec_Ult_ModField.Equals(value) != true)) {
                    this.Fec_Ult_ModField = value;
                    this.RaisePropertyChanged("Fec_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_cli {
            get {
                return this.Nom_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_cliField, value) != true)) {
                    this.Nom_cliField = value;
                    this.RaisePropertyChanged("Nom_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Raz_soc_cli {
            get {
                return this.Raz_soc_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Raz_soc_cliField, value) != true)) {
                    this.Raz_soc_cliField = value;
                    this.RaisePropertyChanged("Raz_soc_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruc_Cli {
            get {
                return this.Ruc_CliField;
            }
            set {
                if ((object.ReferenceEquals(this.Ruc_CliField, value) != true)) {
                    this.Ruc_CliField = value;
                    this.RaisePropertyChanged("Ruc_Cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telf_Cli {
            get {
                return this.Telf_CliField;
            }
            set {
                if ((object.ReferenceEquals(this.Telf_CliField, value) != true)) {
                    this.Telf_CliField = value;
                    this.RaisePropertyChanged("Telf_Cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float TipoCliente {
            get {
                return this.TipoClienteField;
            }
            set {
                if ((this.TipoClienteField.Equals(value) != true)) {
                    this.TipoClienteField = value;
                    this.RaisePropertyChanged("TipoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro {
            get {
                return this.Usu_RegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_RegistroField, value) != true)) {
                    this.Usu_RegistroField = value;
                    this.RaisePropertyChanged("Usu_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_ubigeo {
            get {
                return this.cod_ubigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_ubigeoField, value) != true)) {
                    this.cod_ubigeoField = value;
                    this.RaisePropertyChanged("cod_ubigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dir_cli {
            get {
                return this.dir_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.dir_cliField, value) != true)) {
                    this.dir_cliField = value;
                    this.RaisePropertyChanged("dir_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idCliente {
            get {
                return this.idClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.idClienteField, value) != true)) {
                    this.idClienteField = value;
                    this.RaisePropertyChanged("idCliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteFecDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Mant")]
    [System.SerializableAttribute()]
    public partial class ClienteFecDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ape_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ape_mecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dni_CliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float Est_CliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float Est_MecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoMecanicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_Mant_FinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_Mant_InicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_mecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Raz_soc_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ruc_CliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoUnidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float Tipo_UnidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idMarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idVehiculoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_cli {
            get {
                return this.Ape_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Ape_cliField, value) != true)) {
                    this.Ape_cliField = value;
                    this.RaisePropertyChanged("Ape_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_mec {
            get {
                return this.Ape_mecField;
            }
            set {
                if ((object.ReferenceEquals(this.Ape_mecField, value) != true)) {
                    this.Ape_mecField = value;
                    this.RaisePropertyChanged("Ape_mec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni_Cli {
            get {
                return this.Dni_CliField;
            }
            set {
                if ((object.ReferenceEquals(this.Dni_CliField, value) != true)) {
                    this.Dni_CliField = value;
                    this.RaisePropertyChanged("Dni_Cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Est_Cli {
            get {
                return this.Est_CliField;
            }
            set {
                if ((this.Est_CliField.Equals(value) != true)) {
                    this.Est_CliField = value;
                    this.RaisePropertyChanged("Est_Cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Est_Mec {
            get {
                return this.Est_MecField;
            }
            set {
                if ((this.Est_MecField.Equals(value) != true)) {
                    this.Est_MecField = value;
                    this.RaisePropertyChanged("Est_Mec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoCliente {
            get {
                return this.EstadoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoClienteField, value) != true)) {
                    this.EstadoClienteField = value;
                    this.RaisePropertyChanged("EstadoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoMecanico {
            get {
                return this.EstadoMecanicoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoMecanicoField, value) != true)) {
                    this.EstadoMecanicoField = value;
                    this.RaisePropertyChanged("EstadoMecanico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Mant_Fin {
            get {
                return this.Fec_Mant_FinField;
            }
            set {
                if ((this.Fec_Mant_FinField.Equals(value) != true)) {
                    this.Fec_Mant_FinField = value;
                    this.RaisePropertyChanged("Fec_Mant_Fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Mant_Inic {
            get {
                return this.Fec_Mant_InicField;
            }
            set {
                if ((this.Fec_Mant_InicField.Equals(value) != true)) {
                    this.Fec_Mant_InicField = value;
                    this.RaisePropertyChanged("Fec_Mant_Inic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_cli {
            get {
                return this.Nom_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_cliField, value) != true)) {
                    this.Nom_cliField = value;
                    this.RaisePropertyChanged("Nom_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_mec {
            get {
                return this.Nom_mecField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_mecField, value) != true)) {
                    this.Nom_mecField = value;
                    this.RaisePropertyChanged("Nom_mec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Raz_soc_cli {
            get {
                return this.Raz_soc_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Raz_soc_cliField, value) != true)) {
                    this.Raz_soc_cliField = value;
                    this.RaisePropertyChanged("Raz_soc_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruc_Cli {
            get {
                return this.Ruc_CliField;
            }
            set {
                if ((object.ReferenceEquals(this.Ruc_CliField, value) != true)) {
                    this.Ruc_CliField = value;
                    this.RaisePropertyChanged("Ruc_Cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoUnidad {
            get {
                return this.TipoUnidadField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoUnidadField, value) != true)) {
                    this.TipoUnidadField = value;
                    this.RaisePropertyChanged("TipoUnidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Tipo_Unidad {
            get {
                return this.Tipo_UnidadField;
            }
            set {
                if ((this.Tipo_UnidadField.Equals(value) != true)) {
                    this.Tipo_UnidadField = value;
                    this.RaisePropertyChanged("Tipo_Unidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idCliente {
            get {
                return this.idClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.idClienteField, value) != true)) {
                    this.idClienteField = value;
                    this.RaisePropertyChanged("idCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idMarca {
            get {
                return this.idMarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.idMarcaField, value) != true)) {
                    this.idMarcaField = value;
                    this.RaisePropertyChanged("idMarca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idVehiculo {
            get {
                return this.idVehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.idVehiculoField, value) != true)) {
                    this.idVehiculoField = value;
                    this.RaisePropertyChanged("idVehiculo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyClientes.IServicioCliente")]
    public interface IServicioCliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ConsultarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ConsultarClienteResponse")]
        Mantenimiento_WCF_MVC.ProxyClientes.ClienteDC ConsultarCliente(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ConsultarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ConsultarClienteResponse")]
        System.Threading.Tasks.Task<Mantenimiento_WCF_MVC.ProxyClientes.ClienteDC> ConsultarClienteAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ListarClienteFechas", ReplyAction="http://tempuri.org/IServicioCliente/ListarClienteFechasResponse")]
        Mantenimiento_WCF_MVC.ProxyClientes.ClienteFecDC[] ListarClienteFechas(string strCliente, System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ListarClienteFechas", ReplyAction="http://tempuri.org/IServicioCliente/ListarClienteFechasResponse")]
        System.Threading.Tasks.Task<Mantenimiento_WCF_MVC.ProxyClientes.ClienteFecDC[]> ListarClienteFechasAsync(string strCliente, System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ListarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ListarClienteResponse")]
        Mantenimiento_WCF_MVC.ProxyClientes.ClienteDC[] ListarCliente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ListarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ListarClienteResponse")]
        System.Threading.Tasks.Task<Mantenimiento_WCF_MVC.ProxyClientes.ClienteDC[]> ListarClienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/InsertarCliente", ReplyAction="http://tempuri.org/IServicioCliente/InsertarClienteResponse")]
        bool InsertarCliente(Mantenimiento_WCF_MVC.ProxyClientes.ClienteDC objClienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/InsertarCliente", ReplyAction="http://tempuri.org/IServicioCliente/InsertarClienteResponse")]
        System.Threading.Tasks.Task<bool> InsertarClienteAsync(Mantenimiento_WCF_MVC.ProxyClientes.ClienteDC objClienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ActualizarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ActualizarClienteResponse")]
        bool ActualizarCliente(Mantenimiento_WCF_MVC.ProxyClientes.ClienteDC objClienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ActualizarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ActualizarClienteResponse")]
        System.Threading.Tasks.Task<bool> ActualizarClienteAsync(Mantenimiento_WCF_MVC.ProxyClientes.ClienteDC objClienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/EliminarCliente", ReplyAction="http://tempuri.org/IServicioCliente/EliminarClienteResponse")]
        bool EliminarCliente(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/EliminarCliente", ReplyAction="http://tempuri.org/IServicioCliente/EliminarClienteResponse")]
        System.Threading.Tasks.Task<bool> EliminarClienteAsync(string strCodigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioClienteChannel : Mantenimiento_WCF_MVC.ProxyClientes.IServicioCliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClienteClient : System.ServiceModel.ClientBase<Mantenimiento_WCF_MVC.ProxyClientes.IServicioCliente>, Mantenimiento_WCF_MVC.ProxyClientes.IServicioCliente {
        
        public ServicioClienteClient() {
        }
        
        public ServicioClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Mantenimiento_WCF_MVC.ProxyClientes.ClienteDC ConsultarCliente(string strCodigo) {
            return base.Channel.ConsultarCliente(strCodigo);
        }
        
        public System.Threading.Tasks.Task<Mantenimiento_WCF_MVC.ProxyClientes.ClienteDC> ConsultarClienteAsync(string strCodigo) {
            return base.Channel.ConsultarClienteAsync(strCodigo);
        }
        
        public Mantenimiento_WCF_MVC.ProxyClientes.ClienteFecDC[] ListarClienteFechas(string strCliente, System.DateTime fecini, System.DateTime fecfin) {
            return base.Channel.ListarClienteFechas(strCliente, fecini, fecfin);
        }
        
        public System.Threading.Tasks.Task<Mantenimiento_WCF_MVC.ProxyClientes.ClienteFecDC[]> ListarClienteFechasAsync(string strCliente, System.DateTime fecini, System.DateTime fecfin) {
            return base.Channel.ListarClienteFechasAsync(strCliente, fecini, fecfin);
        }
        
        public Mantenimiento_WCF_MVC.ProxyClientes.ClienteDC[] ListarCliente() {
            return base.Channel.ListarCliente();
        }
        
        public System.Threading.Tasks.Task<Mantenimiento_WCF_MVC.ProxyClientes.ClienteDC[]> ListarClienteAsync() {
            return base.Channel.ListarClienteAsync();
        }
        
        public bool InsertarCliente(Mantenimiento_WCF_MVC.ProxyClientes.ClienteDC objClienteDC) {
            return base.Channel.InsertarCliente(objClienteDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarClienteAsync(Mantenimiento_WCF_MVC.ProxyClientes.ClienteDC objClienteDC) {
            return base.Channel.InsertarClienteAsync(objClienteDC);
        }
        
        public bool ActualizarCliente(Mantenimiento_WCF_MVC.ProxyClientes.ClienteDC objClienteDC) {
            return base.Channel.ActualizarCliente(objClienteDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarClienteAsync(Mantenimiento_WCF_MVC.ProxyClientes.ClienteDC objClienteDC) {
            return base.Channel.ActualizarClienteAsync(objClienteDC);
        }
        
        public bool EliminarCliente(string strCodigo) {
            return base.Channel.EliminarCliente(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarClienteAsync(string strCodigo) {
            return base.Channel.EliminarClienteAsync(strCodigo);
        }
    }
}
